name: go_fetch
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - getorganelle =1.7.7.0
  - spades =3.15.5
  - scipy =1.11.3
  - gzip =1.12
  - biopython =biopython=1.81
  - trf =4.07b-0
